import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '3.3.1:33',
  releaseNotes: {
    en_US: `Fixes the explorer against a node that is not the official Bitcoin package, and against any node that is not on mainnet. Two faults with one cause: what the explorer read the node's credentials from did not follow which node you selected, or which chain it was on. It always looked inside the official Bitcoin package's data, at the location used only on mainnet. Selecting a different node therefore pointed the explorer at that node while reading credentials belonging to another, and on a private chain it read a location that does not exist there. Either way the explorer could not authenticate and never indexed. Mainnet with the official package, which is what most installs run, was unaffected. Both now follow the node you selected and the chain it reports, and a chain change restarts the explorer rather than leaving it reading a path that has moved. Nothing you have set changes and no re-index is needed.`,
    es_ES: `Fixes the explorer against a node that is not the official Bitcoin package, and against any node that is not on mainnet. Two faults with one cause: what the explorer read the node's credentials from did not follow which node you selected, or which chain it was on. It always looked inside the official Bitcoin package's data, at the location used only on mainnet. Selecting a different node therefore pointed the explorer at that node while reading credentials belonging to another, and on a private chain it read a location that does not exist there. Either way the explorer could not authenticate and never indexed. Mainnet with the official package, which is what most installs run, was unaffected. Both now follow the node you selected and the chain it reports, and a chain change restarts the explorer rather than leaving it reading a path that has moved. Nothing you have set changes and no re-index is needed.`,
    de_DE: `Fixes the explorer against a node that is not the official Bitcoin package, and against any node that is not on mainnet. Two faults with one cause: what the explorer read the node's credentials from did not follow which node you selected, or which chain it was on. It always looked inside the official Bitcoin package's data, at the location used only on mainnet. Selecting a different node therefore pointed the explorer at that node while reading credentials belonging to another, and on a private chain it read a location that does not exist there. Either way the explorer could not authenticate and never indexed. Mainnet with the official package, which is what most installs run, was unaffected. Both now follow the node you selected and the chain it reports, and a chain change restarts the explorer rather than leaving it reading a path that has moved. Nothing you have set changes and no re-index is needed.`,
    pl_PL: `Fixes the explorer against a node that is not the official Bitcoin package, and against any node that is not on mainnet. Two faults with one cause: what the explorer read the node's credentials from did not follow which node you selected, or which chain it was on. It always looked inside the official Bitcoin package's data, at the location used only on mainnet. Selecting a different node therefore pointed the explorer at that node while reading credentials belonging to another, and on a private chain it read a location that does not exist there. Either way the explorer could not authenticate and never indexed. Mainnet with the official package, which is what most installs run, was unaffected. Both now follow the node you selected and the chain it reports, and a chain change restarts the explorer rather than leaving it reading a path that has moved. Nothing you have set changes and no re-index is needed.`,
    fr_FR: `Fixes the explorer against a node that is not the official Bitcoin package, and against any node that is not on mainnet. Two faults with one cause: what the explorer read the node's credentials from did not follow which node you selected, or which chain it was on. It always looked inside the official Bitcoin package's data, at the location used only on mainnet. Selecting a different node therefore pointed the explorer at that node while reading credentials belonging to another, and on a private chain it read a location that does not exist there. Either way the explorer could not authenticate and never indexed. Mainnet with the official package, which is what most installs run, was unaffected. Both now follow the node you selected and the chain it reports, and a chain change restarts the explorer rather than leaving it reading a path that has moved. Nothing you have set changes and no re-index is needed.`,
  },
  migrations: {
    // Nothing to migrate. COOKIE_PATH stops being a fixed value and is derived on every start
    // instead, so whatever an existing config holds is overwritten with the right one the first
    // time this runs. Widening its schema from a literal to a string cannot reject an existing
    // config either, since the value it used to be pinned to is still a valid string.
    //
    // The RDTS remap, retry default and stale-task cleanup that :31 needed live
    // in `v3.3.1_31.ts`, with the version that introduced them.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
