import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '3.3.1:34',
  releaseNotes: {
    en_US: `Fixes the explorer falling behind the chain on a pruned node, and gives every block a miner name.\n\nThe explorer worked out each transaction's fee by reading every input's previous transaction. On a pruned node those sit in blocks your node no longer keeps, so each one became a block fetch from a peer. One recent block needed 288 of them. That took longer than the time between blocks, so the explorer fell further behind with every block, eventually gave up and showed only the eight most recent, and stopped serving history. It now reads the whole block from your node in one call, which supplies the fees as well, and only falls back to the slower route for blocks your node has pruned. A block that took minutes now takes milliseconds. Nothing you have set changes, and the history already indexed is still there.\n\nBlocks whose miner is not in the known pool list now show the name the miner wrote into the block itself, rather than Unknown. A recognised pool still shows its own name and icon, and mining statistics still count self-named miners as unattributed, because a name somebody chose for themselves is not a pool.\n\nThe optional indexing features are usable on a pruned node for the first time. Block Summaries, Goggles and CPFP all read whole blocks, and the indexing window is a year of them by default, so on a node keeping a few thousand they would have aimed tens of thousands at blocks it no longer has and taken the explorer down with them. They now stop where your node's blocks stop, and a single block that cannot be read is skipped and named rather than restarting the whole backfill every ten seconds. Block Audit needs none of this and was already safe.`,
    es_ES: `Fixes the explorer falling behind the chain on a pruned node, and gives every block a miner name.\n\nThe explorer worked out each transaction's fee by reading every input's previous transaction. On a pruned node those sit in blocks your node no longer keeps, so each one became a block fetch from a peer. One recent block needed 288 of them. That took longer than the time between blocks, so the explorer fell further behind with every block, eventually gave up and showed only the eight most recent, and stopped serving history. It now reads the whole block from your node in one call, which supplies the fees as well, and only falls back to the slower route for blocks your node has pruned. A block that took minutes now takes milliseconds. Nothing you have set changes, and the history already indexed is still there.\n\nBlocks whose miner is not in the known pool list now show the name the miner wrote into the block itself, rather than Unknown. A recognised pool still shows its own name and icon, and mining statistics still count self-named miners as unattributed, because a name somebody chose for themselves is not a pool.\n\nThe optional indexing features are usable on a pruned node for the first time. Block Summaries, Goggles and CPFP all read whole blocks, and the indexing window is a year of them by default, so on a node keeping a few thousand they would have aimed tens of thousands at blocks it no longer has and taken the explorer down with them. They now stop where your node's blocks stop, and a single block that cannot be read is skipped and named rather than restarting the whole backfill every ten seconds. Block Audit needs none of this and was already safe.`,
    de_DE: `Fixes the explorer falling behind the chain on a pruned node, and gives every block a miner name.\n\nThe explorer worked out each transaction's fee by reading every input's previous transaction. On a pruned node those sit in blocks your node no longer keeps, so each one became a block fetch from a peer. One recent block needed 288 of them. That took longer than the time between blocks, so the explorer fell further behind with every block, eventually gave up and showed only the eight most recent, and stopped serving history. It now reads the whole block from your node in one call, which supplies the fees as well, and only falls back to the slower route for blocks your node has pruned. A block that took minutes now takes milliseconds. Nothing you have set changes, and the history already indexed is still there.\n\nBlocks whose miner is not in the known pool list now show the name the miner wrote into the block itself, rather than Unknown. A recognised pool still shows its own name and icon, and mining statistics still count self-named miners as unattributed, because a name somebody chose for themselves is not a pool.\n\nThe optional indexing features are usable on a pruned node for the first time. Block Summaries, Goggles and CPFP all read whole blocks, and the indexing window is a year of them by default, so on a node keeping a few thousand they would have aimed tens of thousands at blocks it no longer has and taken the explorer down with them. They now stop where your node's blocks stop, and a single block that cannot be read is skipped and named rather than restarting the whole backfill every ten seconds. Block Audit needs none of this and was already safe.`,
    pl_PL: `Fixes the explorer falling behind the chain on a pruned node, and gives every block a miner name.\n\nThe explorer worked out each transaction's fee by reading every input's previous transaction. On a pruned node those sit in blocks your node no longer keeps, so each one became a block fetch from a peer. One recent block needed 288 of them. That took longer than the time between blocks, so the explorer fell further behind with every block, eventually gave up and showed only the eight most recent, and stopped serving history. It now reads the whole block from your node in one call, which supplies the fees as well, and only falls back to the slower route for blocks your node has pruned. A block that took minutes now takes milliseconds. Nothing you have set changes, and the history already indexed is still there.\n\nBlocks whose miner is not in the known pool list now show the name the miner wrote into the block itself, rather than Unknown. A recognised pool still shows its own name and icon, and mining statistics still count self-named miners as unattributed, because a name somebody chose for themselves is not a pool.\n\nThe optional indexing features are usable on a pruned node for the first time. Block Summaries, Goggles and CPFP all read whole blocks, and the indexing window is a year of them by default, so on a node keeping a few thousand they would have aimed tens of thousands at blocks it no longer has and taken the explorer down with them. They now stop where your node's blocks stop, and a single block that cannot be read is skipped and named rather than restarting the whole backfill every ten seconds. Block Audit needs none of this and was already safe.`,
    fr_FR: `Fixes the explorer falling behind the chain on a pruned node, and gives every block a miner name.\n\nThe explorer worked out each transaction's fee by reading every input's previous transaction. On a pruned node those sit in blocks your node no longer keeps, so each one became a block fetch from a peer. One recent block needed 288 of them. That took longer than the time between blocks, so the explorer fell further behind with every block, eventually gave up and showed only the eight most recent, and stopped serving history. It now reads the whole block from your node in one call, which supplies the fees as well, and only falls back to the slower route for blocks your node has pruned. A block that took minutes now takes milliseconds. Nothing you have set changes, and the history already indexed is still there.\n\nBlocks whose miner is not in the known pool list now show the name the miner wrote into the block itself, rather than Unknown. A recognised pool still shows its own name and icon, and mining statistics still count self-named miners as unattributed, because a name somebody chose for themselves is not a pool.\n\nThe optional indexing features are usable on a pruned node for the first time. Block Summaries, Goggles and CPFP all read whole blocks, and the indexing window is a year of them by default, so on a node keeping a few thousand they would have aimed tens of thousands at blocks it no longer has and taken the explorer down with them. They now stop where your node's blocks stop, and a single block that cannot be read is skipped and named rather than restarting the whole backfill every ten seconds. Block Audit needs none of this and was already safe.`,
  },
  migrations: {
    // Nothing to migrate. Both changes are in the backend image: which route reads a
    // block's transactions, and what a block is labelled with when no pool matches.
    // Neither touches stored config or the database schema, and blocks already indexed
    // keep their rows. The miner name is derived on read from the coinbase the blocks
    // table already stores, so it appears on old blocks too without a re-index.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
